/* automatically generated by rust-bindgen 0.72.1 */

// Ghostty source: 4c6215bb8ee186b5c829457a9a9a9c936f2337bf; public-header fingerprint: fnv1a64:610046ed84d97e2e

pub const ENUM_MAX_VALUE: u32 = 2147483647;
pub const COLOR_NAMED_BLACK: u8 = 0;
pub const COLOR_NAMED_RED: u8 = 1;
pub const COLOR_NAMED_GREEN: u8 = 2;
pub const COLOR_NAMED_YELLOW: u8 = 3;
pub const COLOR_NAMED_BLUE: u8 = 4;
pub const COLOR_NAMED_MAGENTA: u8 = 5;
pub const COLOR_NAMED_CYAN: u8 = 6;
pub const COLOR_NAMED_WHITE: u8 = 7;
pub const COLOR_NAMED_BRIGHT_BLACK: u8 = 8;
pub const COLOR_NAMED_BRIGHT_RED: u8 = 9;
pub const COLOR_NAMED_BRIGHT_GREEN: u8 = 10;
pub const COLOR_NAMED_BRIGHT_YELLOW: u8 = 11;
pub const COLOR_NAMED_BRIGHT_BLUE: u8 = 12;
pub const COLOR_NAMED_BRIGHT_MAGENTA: u8 = 13;
pub const COLOR_NAMED_BRIGHT_CYAN: u8 = 14;
pub const COLOR_NAMED_BRIGHT_WHITE: u8 = 15;
pub const DA_CONFORMANCE_VT100: u16 = 1;
pub const DA_CONFORMANCE_VT101: u16 = 1;
pub const DA_CONFORMANCE_VT102: u16 = 6;
pub const DA_CONFORMANCE_VT125: u16 = 12;
pub const DA_CONFORMANCE_VT131: u16 = 7;
pub const DA_CONFORMANCE_VT132: u16 = 4;
pub const DA_CONFORMANCE_VT220: u16 = 62;
pub const DA_CONFORMANCE_VT240: u16 = 62;
pub const DA_CONFORMANCE_VT320: u16 = 63;
pub const DA_CONFORMANCE_VT340: u16 = 63;
pub const DA_CONFORMANCE_VT420: u16 = 64;
pub const DA_CONFORMANCE_VT510: u16 = 65;
pub const DA_CONFORMANCE_VT520: u16 = 65;
pub const DA_CONFORMANCE_VT525: u16 = 65;
pub const DA_CONFORMANCE_LEVEL_2: u16 = 62;
pub const DA_CONFORMANCE_LEVEL_3: u16 = 63;
pub const DA_CONFORMANCE_LEVEL_4: u16 = 64;
pub const DA_CONFORMANCE_LEVEL_5: u16 = 65;
pub const DA_FEATURE_COLUMNS_132: u16 = 1;
pub const DA_FEATURE_PRINTER: u16 = 2;
pub const DA_FEATURE_REGIS: u16 = 3;
pub const DA_FEATURE_SIXEL: u16 = 4;
pub const DA_FEATURE_SELECTIVE_ERASE: u16 = 6;
pub const DA_FEATURE_USER_DEFINED_KEYS: u16 = 8;
pub const DA_FEATURE_NATIONAL_REPLACEMENT: u16 = 9;
pub const DA_FEATURE_TECHNICAL_CHARACTERS: u16 = 15;
pub const DA_FEATURE_LOCATOR: u16 = 16;
pub const DA_FEATURE_TERMINAL_STATE: u16 = 17;
pub const DA_FEATURE_WINDOWING: u16 = 18;
pub const DA_FEATURE_HORIZONTAL_SCROLLING: u16 = 21;
pub const DA_FEATURE_ANSI_COLOR: u16 = 22;
pub const DA_FEATURE_RECTANGULAR_EDITING: u16 = 28;
pub const DA_FEATURE_ANSI_TEXT_LOCATOR: u16 = 29;
pub const DA_FEATURE_CLIPBOARD: u16 = 52;
pub const DA_DEVICE_TYPE_VT100: u16 = 0;
pub const DA_DEVICE_TYPE_VT220: u16 = 1;
pub const DA_DEVICE_TYPE_VT240: u16 = 2;
pub const DA_DEVICE_TYPE_VT330: u16 = 18;
pub const DA_DEVICE_TYPE_VT340: u16 = 19;
pub const DA_DEVICE_TYPE_VT320: u16 = 24;
pub const DA_DEVICE_TYPE_VT382: u16 = 32;
pub const DA_DEVICE_TYPE_VT420: u16 = 41;
pub const DA_DEVICE_TYPE_VT510: u16 = 61;
pub const DA_DEVICE_TYPE_VT520: u16 = 64;
pub const DA_DEVICE_TYPE_VT525: u16 = 65;
pub const MODS_SHIFT: u16 = 1;
pub const MODS_CTRL: u16 = 2;
pub const MODS_ALT: u16 = 4;
pub const MODS_SUPER: u16 = 8;
pub const MODS_CAPS_LOCK: u16 = 16;
pub const MODS_NUM_LOCK: u16 = 32;
pub const MODS_SHIFT_SIDE: u16 = 64;
pub const MODS_CTRL_SIDE: u16 = 128;
pub const MODS_ALT_SIDE: u16 = 256;
pub const MODS_SUPER_SIDE: u16 = 512;
pub const KITTY_KEY_DISABLED: u8 = 0;
pub const KITTY_KEY_DISAMBIGUATE: u8 = 1;
pub const KITTY_KEY_REPORT_EVENTS: u8 = 2;
pub const KITTY_KEY_REPORT_ALTERNATES: u8 = 4;
pub const KITTY_KEY_REPORT_ALL: u8 = 8;
pub const KITTY_KEY_REPORT_ASSOCIATED: u8 = 16;
pub const KITTY_KEY_ALL: u8 = 31;
pub mod Result {
    pub type Type = ::std::os::raw::c_int;
    pub const SUCCESS: Type = 0;
    pub const OUT_OF_MEMORY: Type = -1;
    pub const INVALID_VALUE: Type = -2;
    pub const OUT_OF_SPACE: Type = -3;
    pub const NO_VALUE: Type = -4;
    pub const IO_ERROR: Type = -5;
    pub const LIMIT_EXCEEDED: Type = -6;
    pub const RESULT_MAX_VALUE: Type = 2147483647;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TerminalImpl {
    _unused: [u8; 0],
}
pub type Terminal = *mut TerminalImpl;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SnapshotDecoderImpl {
    _unused: [u8; 0],
}
pub type SnapshotDecoder = *mut SnapshotDecoderImpl;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TrackedGridRefImpl {
    _unused: [u8; 0],
}
pub type TrackedGridRef = *mut TrackedGridRefImpl;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KittyGraphicsImpl {
    _unused: [u8; 0],
}
pub type KittyGraphics = *mut KittyGraphicsImpl;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KittyGraphicsImageImpl {
    _unused: [u8; 0],
}
pub type KittyGraphicsImage = *const KittyGraphicsImageImpl;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KittyGraphicsPlacementIteratorImpl {
    _unused: [u8; 0],
}
pub type KittyGraphicsPlacementIterator = *mut KittyGraphicsPlacementIteratorImpl;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RenderStateImpl {
    _unused: [u8; 0],
}
pub type RenderState = *mut RenderStateImpl;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RenderStateRowIteratorImpl {
    _unused: [u8; 0],
}
pub type RenderStateRowIterator = *mut RenderStateRowIteratorImpl;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RenderStateRowCellsImpl {
    _unused: [u8; 0],
}
pub type RenderStateRowCells = *mut RenderStateRowCellsImpl;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SgrParserImpl {
    _unused: [u8; 0],
}
pub type SgrParser = *mut SgrParserImpl;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FormatterImpl {
    _unused: [u8; 0],
}
pub type Formatter = *mut FormatterImpl;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OscParserImpl {
    _unused: [u8; 0],
}
pub type OscParser = *mut OscParserImpl;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OscCommandImpl {
    _unused: [u8; 0],
}
pub type OscCommand = *mut OscCommandImpl;
pub mod FormatterFormat {
    pub type Type = ::std::os::raw::c_int;
    pub const PLAIN: Type = 0;
    pub const VT: Type = 1;
    pub const HTML: Type = 2;
    pub const MAX_VALUE: Type = 2147483647;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct String {
    pub ptr: *const u8,
    pub len: usize,
}
impl Default for String {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Buffer {
    pub ptr: *mut u8,
    pub cap: usize,
    pub len: usize,
}
impl Default for Buffer {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct SurfacePosition {
    pub x: f64,
    pub y: f64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Codepoints {
    pub ptr: *const u32,
    pub len: usize,
}
impl Default for Codepoints {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn ghostty_type_json() -> *const ::std::os::raw::c_char;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct AllocatorVtable {
    pub alloc: ::std::option::Option<
        unsafe extern "C" fn(
            ctx: *mut ::std::os::raw::c_void,
            len: usize,
            alignment: u8,
            ret_addr: usize,
        ) -> *mut ::std::os::raw::c_void,
    >,
    pub resize: ::std::option::Option<
        unsafe extern "C" fn(
            ctx: *mut ::std::os::raw::c_void,
            memory: *mut ::std::os::raw::c_void,
            memory_len: usize,
            alignment: u8,
            new_len: usize,
            ret_addr: usize,
        ) -> bool,
    >,
    pub remap: ::std::option::Option<
        unsafe extern "C" fn(
            ctx: *mut ::std::os::raw::c_void,
            memory: *mut ::std::os::raw::c_void,
            memory_len: usize,
            alignment: u8,
            new_len: usize,
            ret_addr: usize,
        ) -> *mut ::std::os::raw::c_void,
    >,
    pub free: ::std::option::Option<
        unsafe extern "C" fn(
            ctx: *mut ::std::os::raw::c_void,
            memory: *mut ::std::os::raw::c_void,
            memory_len: usize,
            alignment: u8,
            ret_addr: usize,
        ),
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Allocator {
    pub ctx: *mut ::std::os::raw::c_void,
    pub vtable: *const AllocatorVtable,
}
impl Default for Allocator {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn ghostty_alloc(allocator: *const Allocator, len: usize) -> *mut u8;
}
unsafe extern "C" {
    pub fn ghostty_free(allocator: *const Allocator, ptr: *mut u8, len: usize);
}
pub mod OptimizeMode {
    pub type Type = ::std::os::raw::c_int;
    pub const DEBUG: Type = 0;
    pub const RELEASE_SAFE: Type = 1;
    pub const RELEASE_SMALL: Type = 2;
    pub const RELEASE_FAST: Type = 3;
    pub const MODE_MAX_VALUE: Type = 2147483647;
}
pub mod BuildInfo {
    pub type Type = ::std::os::raw::c_int;
    pub const INVALID: Type = 0;
    pub const SIMD: Type = 1;
    pub const KITTY_GRAPHICS: Type = 2;
    pub const TMUX_CONTROL_MODE: Type = 3;
    pub const OPTIMIZE: Type = 4;
    pub const VERSION_STRING: Type = 5;
    pub const VERSION_MAJOR: Type = 6;
    pub const VERSION_MINOR: Type = 7;
    pub const VERSION_PATCH: Type = 8;
    pub const VERSION_PRE: Type = 9;
    pub const VERSION_BUILD: Type = 10;
    pub const MAX_VALUE: Type = 2147483647;
}
unsafe extern "C" {
    pub fn ghostty_build_info(
        data: BuildInfo::Type,
        out: *mut ::std::os::raw::c_void,
    ) -> Result::Type;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct ColorRgb {
    pub r: u8,
    pub g: u8,
    pub b: u8,
}
pub type ColorPaletteIndex = u8;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct ColorPaletteMask {
    pub bits: [u64; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ColorX11Entry {
    pub name: *const ::std::os::raw::c_char,
    pub color: ColorRgb,
}
impl Default for ColorX11Entry {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn ghostty_color_rgb_get(color: *const ColorRgb, r: *mut u8, g: *mut u8, b: *mut u8);
}
unsafe extern "C" {
    pub fn ghostty_color_parse_x11(
        name: *const ::std::os::raw::c_char,
        len: usize,
        out: *mut ColorRgb,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_color_parse(
        value: *const ::std::os::raw::c_char,
        len: usize,
        out: *mut ColorRgb,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_color_parse_palette_entry(
        value: *const ::std::os::raw::c_char,
        len: usize,
        out_index: *mut u8,
        out_rgb: *mut ColorRgb,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_color_palette_default(out: *mut ColorRgb);
}
unsafe extern "C" {
    pub fn ghostty_color_palette_generate(
        base: *const ColorRgb,
        skip: *const ColorPaletteMask,
        bg: *const ColorRgb,
        fg: *const ColorRgb,
        harmonious: bool,
        out: *mut ColorRgb,
    );
}
unsafe extern "C" {
    pub fn ghostty_color_luminance(color: *const ColorRgb) -> f64;
}
unsafe extern "C" {
    pub fn ghostty_color_perceived_luminance(color: *const ColorRgb) -> f64;
}
unsafe extern "C" {
    pub fn ghostty_color_contrast(a: *const ColorRgb, b: *const ColorRgb) -> f64;
}
unsafe extern "C" {
    pub fn ghostty_color_x11_names() -> *const ColorX11Entry;
}
unsafe extern "C" {
    pub fn ghostty_color_x11_name_count() -> usize;
}
pub mod ColorScheme {
    pub type Type = ::std::os::raw::c_int;
    pub const LIGHT: Type = 0;
    pub const DARK: Type = 1;
    pub const MAX_VALUE: Type = 2147483647;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DeviceAttributesPrimary {
    pub conformance_level: u16,
    pub features: [u16; 64usize],
    pub num_features: usize,
}
impl Default for DeviceAttributesPrimary {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct DeviceAttributesSecondary {
    pub device_type: u16,
    pub firmware_version: u16,
    pub rom_cartridge: u16,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct DeviceAttributesTertiary {
    pub unit_id: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DeviceAttributes {
    pub primary: DeviceAttributesPrimary,
    pub secondary: DeviceAttributesSecondary,
    pub tertiary: DeviceAttributesTertiary,
}
impl Default for DeviceAttributes {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn ghostty_color_scheme_report_encode(
        scheme: ColorScheme::Type,
        buf: *mut ::std::os::raw::c_char,
        buf_len: usize,
        out_written: *mut usize,
    ) -> Result::Type;
}
pub mod FocusEvent {
    pub type Type = ::std::os::raw::c_int;
    pub const GAINED: Type = 0;
    pub const LOST: Type = 1;
    pub const MAX_VALUE: Type = 2147483647;
}
unsafe extern "C" {
    pub fn ghostty_focus_encode(
        event: FocusEvent::Type,
        buf: *mut ::std::os::raw::c_char,
        buf_len: usize,
        out_written: *mut usize,
    ) -> Result::Type;
}
pub type ReaderFn = ::std::option::Option<
    unsafe extern "C" fn(
        userdata: *mut ::std::os::raw::c_void,
        buffer: *mut u8,
        capacity: usize,
        out_read: *mut usize,
    ) -> bool,
>;
pub type WriterFn = ::std::option::Option<
    unsafe extern "C" fn(
        userdata: *mut ::std::os::raw::c_void,
        data: *const u8,
        len: usize,
    ) -> bool,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Reader {
    pub read: ReaderFn,
    pub userdata: *mut ::std::os::raw::c_void,
}
impl Default for Reader {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Writer {
    pub write: WriterFn,
    pub userdata: *mut ::std::os::raw::c_void,
}
impl Default for Writer {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type Cell = u64;
pub type Row = u64;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CellsView {
    pub ptr: *const Cell,
    pub len: usize,
}
impl Default for CellsView {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub mod CellContentTag {
    pub type Type = ::std::os::raw::c_int;
    pub const CODEPOINT: Type = 0;
    pub const CODEPOINT_GRAPHEME: Type = 1;
    pub const BG_COLOR_PALETTE: Type = 2;
    pub const BG_COLOR_RGB: Type = 3;
    pub const TAG_MAX_VALUE: Type = 2147483647;
}
pub mod CellWide {
    pub type Type = ::std::os::raw::c_int;
    pub const NARROW: Type = 0;
    pub const WIDE: Type = 1;
    pub const SPACER_TAIL: Type = 2;
    pub const SPACER_HEAD: Type = 3;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod CellSemanticContent {
    pub type Type = ::std::os::raw::c_int;
    pub const OUTPUT: Type = 0;
    pub const INPUT: Type = 1;
    pub const PROMPT: Type = 2;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod CellData {
    pub type Type = ::std::os::raw::c_int;
    pub const INVALID: Type = 0;
    pub const CODEPOINT: Type = 1;
    pub const CONTENT_TAG: Type = 2;
    pub const WIDE: Type = 3;
    pub const HAS_TEXT: Type = 4;
    pub const HAS_STYLING: Type = 5;
    pub const STYLE_ID: Type = 6;
    pub const HAS_HYPERLINK: Type = 7;
    pub const PROTECTED: Type = 8;
    pub const SEMANTIC_CONTENT: Type = 9;
    pub const COLOR_PALETTE: Type = 10;
    pub const COLOR_RGB: Type = 11;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod RowSemanticPrompt {
    pub type Type = ::std::os::raw::c_int;
    pub const NONE: Type = 0;
    pub const PROMPT: Type = 1;
    pub const PROMPT_CONTINUATION: Type = 2;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod RowData {
    pub type Type = ::std::os::raw::c_int;
    pub const INVALID: Type = 0;
    pub const WRAP: Type = 1;
    pub const WRAP_CONTINUATION: Type = 2;
    pub const GRAPHEME: Type = 3;
    pub const STYLED: Type = 4;
    pub const HYPERLINK: Type = 5;
    pub const SEMANTIC_PROMPT: Type = 6;
    pub const KITTY_VIRTUAL_PLACEHOLDER: Type = 7;
    pub const DIRTY: Type = 8;
    pub const MAX_VALUE: Type = 2147483647;
}
unsafe extern "C" {
    pub fn ghostty_cell_get(
        cell: Cell,
        data: CellData::Type,
        out: *mut ::std::os::raw::c_void,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_cell_get_multi(
        cell: Cell,
        count: usize,
        keys: *const CellData::Type,
        values: *mut *mut ::std::os::raw::c_void,
        out_written: *mut usize,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_row_get(
        row: Row,
        data: RowData::Type,
        out: *mut ::std::os::raw::c_void,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_row_get_multi(
        row: Row,
        count: usize,
        keys: *const RowData::Type,
        values: *mut *mut ::std::os::raw::c_void,
        out_written: *mut usize,
    ) -> Result::Type;
}
pub type StyleId = u16;
pub mod StyleColorTag {
    pub type Type = ::std::os::raw::c_int;
    pub const NONE: Type = 0;
    pub const PALETTE: Type = 1;
    pub const RGB: Type = 2;
    pub const TAG_MAX_VALUE: Type = 2147483647;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union StyleColorValue {
    pub palette: ColorPaletteIndex,
    pub rgb: ColorRgb,
    pub _padding: u64,
}
impl Default for StyleColorValue {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct StyleColor {
    pub tag: StyleColorTag::Type,
    pub value: StyleColorValue,
}
impl Default for StyleColor {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct Style {
    pub size: usize,
    pub fg_color: StyleColor,
    pub bg_color: StyleColor,
    pub underline_color: StyleColor,
    pub bold: bool,
    pub italic: bool,
    pub faint: bool,
    pub blink: bool,
    pub inverse: bool,
    pub invisible: bool,
    pub strikethrough: bool,
    pub overline: bool,
    pub underline: ::std::os::raw::c_int,
}
impl Default for Style {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn ghostty_style_default(style: *mut Style);
}
unsafe extern "C" {
    pub fn ghostty_style_is_default(style: *const Style) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GridRef {
    pub size: usize,
    pub node: *mut ::std::os::raw::c_void,
    pub x: u16,
    pub y: u16,
}
impl Default for GridRef {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn ghostty_grid_ref_cell(ref_: *const GridRef, out_cell: *mut Cell) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_grid_ref_row(ref_: *const GridRef, out_row: *mut Row) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_grid_ref_graphemes(
        ref_: *const GridRef,
        buf: *mut u32,
        buf_len: usize,
        out_len: *mut usize,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_grid_ref_hyperlink_uri(
        ref_: *const GridRef,
        buf: *mut u8,
        buf_len: usize,
        out_len: *mut usize,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_grid_ref_style(ref_: *const GridRef, out_style: *mut Style) -> Result::Type;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct PointCoordinate {
    pub x: u16,
    pub y: u32,
}
pub mod PointTag {
    pub type Type = ::std::os::raw::c_int;
    pub const ACTIVE: Type = 0;
    pub const VIEWPORT: Type = 1;
    pub const SCREEN: Type = 2;
    pub const HISTORY: Type = 3;
    pub const MAX_VALUE: Type = 2147483647;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union PointValue {
    pub coordinate: PointCoordinate,
    pub _padding: [u64; 2usize],
}
impl Default for PointValue {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct Point {
    pub tag: PointTag::Type,
    pub value: PointValue,
}
impl Default for Point {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SelectionGestureImpl {
    _unused: [u8; 0],
}
pub type SelectionGesture = *mut SelectionGestureImpl;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SelectionGestureEventImpl {
    _unused: [u8; 0],
}
pub type SelectionGestureEvent = *mut SelectionGestureEventImpl;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Selection {
    pub size: usize,
    pub start: GridRef,
    pub end: GridRef,
    pub rectangle: bool,
}
impl Default for Selection {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TerminalSelectWordOptions {
    pub size: usize,
    pub ref_: GridRef,
    pub boundary_codepoints: *const u32,
    pub boundary_codepoints_len: usize,
}
impl Default for TerminalSelectWordOptions {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TerminalSelectWordBetweenOptions {
    pub size: usize,
    pub start: GridRef,
    pub end: GridRef,
    pub boundary_codepoints: *const u32,
    pub boundary_codepoints_len: usize,
}
impl Default for TerminalSelectWordBetweenOptions {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TerminalSelectLineOptions {
    pub size: usize,
    pub ref_: GridRef,
    pub whitespace: *const u32,
    pub whitespace_len: usize,
    pub semantic_prompt_boundary: bool,
}
impl Default for TerminalSelectLineOptions {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TerminalSelectionFormatOptions {
    pub size: usize,
    pub emit: FormatterFormat::Type,
    pub unwrap: bool,
    pub trim: bool,
    pub selection: *const Selection,
}
impl Default for TerminalSelectionFormatOptions {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub mod SelectionOrder {
    pub type Type = ::std::os::raw::c_int;
    pub const FORWARD: Type = 0;
    pub const REVERSE: Type = 1;
    pub const MIRRORED_FORWARD: Type = 2;
    pub const MIRRORED_REVERSE: Type = 3;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod SelectionAdjust {
    pub type Type = ::std::os::raw::c_int;
    pub const LEFT: Type = 0;
    pub const RIGHT: Type = 1;
    pub const UP: Type = 2;
    pub const DOWN: Type = 3;
    pub const HOME: Type = 4;
    pub const END: Type = 5;
    pub const PAGE_UP: Type = 6;
    pub const PAGE_DOWN: Type = 7;
    pub const BEGINNING_OF_LINE: Type = 8;
    pub const END_OF_LINE: Type = 9;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod SelectionGestureBehavior {
    pub type Type = ::std::os::raw::c_int;
    pub const CELL: Type = 0;
    pub const WORD: Type = 1;
    pub const LINE: Type = 2;
    pub const OUTPUT: Type = 3;
    pub const MAX_VALUE: Type = 2147483647;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SelectionGestureBehaviors {
    pub single_click: SelectionGestureBehavior::Type,
    pub double_click: SelectionGestureBehavior::Type,
    pub triple_click: SelectionGestureBehavior::Type,
}
impl Default for SelectionGestureBehaviors {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct SelectionGestureGeometry {
    pub columns: u32,
    pub cell_width: u32,
    pub padding_left: u32,
    pub screen_height: u32,
}
pub mod SelectionGestureAutoscroll {
    pub type Type = ::std::os::raw::c_int;
    pub const NONE: Type = 0;
    pub const UP: Type = 1;
    pub const DOWN: Type = 2;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod SelectionGestureData {
    pub type Type = ::std::os::raw::c_int;
    pub const CLICK_COUNT: Type = 0;
    pub const DRAGGED: Type = 1;
    pub const AUTOSCROLL: Type = 2;
    pub const BEHAVIOR: Type = 3;
    pub const ANCHOR: Type = 4;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod SelectionGestureEventType {
    pub type Type = ::std::os::raw::c_int;
    pub const PRESS: Type = 0;
    pub const RELEASE: Type = 1;
    pub const DRAG: Type = 2;
    pub const AUTOSCROLL_TICK: Type = 3;
    pub const DEEP_PRESS: Type = 4;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod SelectionGestureEventOption {
    pub type Type = ::std::os::raw::c_int;
    pub const REF: Type = 0;
    pub const POSITION: Type = 1;
    pub const REPEAT_DISTANCE: Type = 2;
    pub const TIME_NS: Type = 3;
    pub const REPEAT_INTERVAL_NS: Type = 4;
    pub const WORD_BOUNDARY_CODEPOINTS: Type = 5;
    pub const BEHAVIORS: Type = 6;
    pub const RECTANGLE: Type = 7;
    pub const GEOMETRY: Type = 8;
    pub const VIEWPORT: Type = 9;
    pub const MAX_VALUE: Type = 2147483647;
}
unsafe extern "C" {
    pub fn ghostty_selection_gesture_event_new(
        allocator: *const Allocator,
        out_event: *mut SelectionGestureEvent,
        type_: SelectionGestureEventType::Type,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_selection_gesture_event_free(event: SelectionGestureEvent);
}
unsafe extern "C" {
    pub fn ghostty_selection_gesture_event_set(
        event: SelectionGestureEvent,
        option: SelectionGestureEventOption::Type,
        value: *const ::std::os::raw::c_void,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_selection_gesture_event(
        gesture: SelectionGesture,
        terminal: Terminal,
        event: SelectionGestureEvent,
        out_selection: *mut Selection,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_selection_gesture_new(
        allocator: *const Allocator,
        out_gesture: *mut SelectionGesture,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_selection_gesture_free(gesture: SelectionGesture, terminal: Terminal);
}
unsafe extern "C" {
    pub fn ghostty_selection_gesture_reset(gesture: SelectionGesture, terminal: Terminal);
}
unsafe extern "C" {
    pub fn ghostty_selection_gesture_get(
        gesture: SelectionGesture,
        terminal: Terminal,
        data: SelectionGestureData::Type,
        value: *mut ::std::os::raw::c_void,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_selection_gesture_get_multi(
        gesture: SelectionGesture,
        terminal: Terminal,
        count: usize,
        keys: *const SelectionGestureData::Type,
        values: *mut *mut ::std::os::raw::c_void,
        out_written: *mut usize,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_select_word(
        terminal: Terminal,
        options: *const TerminalSelectWordOptions,
        out_selection: *mut Selection,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_select_word_between(
        terminal: Terminal,
        options: *const TerminalSelectWordBetweenOptions,
        out_selection: *mut Selection,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_select_line(
        terminal: Terminal,
        options: *const TerminalSelectLineOptions,
        out_selection: *mut Selection,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_select_all(
        terminal: Terminal,
        out_selection: *mut Selection,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_select_output(
        terminal: Terminal,
        ref_: GridRef,
        out_selection: *mut Selection,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_selection_format_buf(
        terminal: Terminal,
        options: TerminalSelectionFormatOptions,
        buf: *mut u8,
        buf_len: usize,
        out_written: *mut usize,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_selection_format_alloc(
        terminal: Terminal,
        allocator: *const Allocator,
        options: TerminalSelectionFormatOptions,
        out_ptr: *mut *mut u8,
        out_len: *mut usize,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_selection_adjust(
        terminal: Terminal,
        selection: *mut Selection,
        adjustment: SelectionAdjust::Type,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_selection_order(
        terminal: Terminal,
        selection: *const Selection,
        out_order: *mut SelectionOrder::Type,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_selection_ordered(
        terminal: Terminal,
        selection: *const Selection,
        desired: SelectionOrder::Type,
        out_selection: *mut Selection,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_selection_contains(
        terminal: Terminal,
        selection: *const Selection,
        point: Point,
        out_contains: *mut bool,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_selection_equal(
        terminal: Terminal,
        a: *const Selection,
        b: *const Selection,
        out_equal: *mut bool,
    ) -> Result::Type;
}
pub type Mode = u16;
pub mod ModeReportState {
    pub type Type = ::std::os::raw::c_int;
    pub const NOT_RECOGNIZED: Type = 0;
    pub const SET: Type = 1;
    pub const RESET: Type = 2;
    pub const PERMANENTLY_SET: Type = 3;
    pub const PERMANENTLY_RESET: Type = 4;
    pub const MAX_VALUE: Type = 2147483647;
}
unsafe extern "C" {
    pub fn ghostty_mode_report_encode(
        mode: Mode,
        state: ModeReportState::Type,
        buf: *mut ::std::os::raw::c_char,
        buf_len: usize,
        out_written: *mut usize,
    ) -> Result::Type;
}
pub mod SizeReportStyle {
    pub type Type = ::std::os::raw::c_int;
    pub const MODE_2048: Type = 0;
    pub const CSI_14_T: Type = 1;
    pub const CSI_16_T: Type = 2;
    pub const CSI_18_T: Type = 3;
    pub const STYLE_MAX_VALUE: Type = 2147483647;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct SizeReportSize {
    pub rows: u16,
    pub columns: u16,
    pub cell_width: u32,
    pub cell_height: u32,
}
unsafe extern "C" {
    pub fn ghostty_size_report_encode(
        style: SizeReportStyle::Type,
        size: SizeReportSize,
        buf: *mut ::std::os::raw::c_char,
        buf_len: usize,
        out_written: *mut usize,
    ) -> Result::Type;
}
pub mod KittyGraphicsData {
    pub type Type = ::std::os::raw::c_int;
    pub const INVALID: Type = 0;
    pub const PLACEMENT_ITERATOR: Type = 1;
    pub const GENERATION: Type = 2;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod KittyGraphicsPlacementData {
    pub type Type = ::std::os::raw::c_int;
    pub const INVALID: Type = 0;
    pub const IMAGE_ID: Type = 1;
    pub const PLACEMENT_ID: Type = 2;
    pub const IS_VIRTUAL: Type = 3;
    pub const X_OFFSET: Type = 4;
    pub const Y_OFFSET: Type = 5;
    pub const SOURCE_X: Type = 6;
    pub const SOURCE_Y: Type = 7;
    pub const SOURCE_WIDTH: Type = 8;
    pub const SOURCE_HEIGHT: Type = 9;
    pub const COLUMNS: Type = 10;
    pub const ROWS: Type = 11;
    pub const Z: Type = 12;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod KittyPlacementLayer {
    pub type Type = ::std::os::raw::c_int;
    pub const ALL: Type = 0;
    pub const BELOW_BG: Type = 1;
    pub const BELOW_TEXT: Type = 2;
    pub const ABOVE_TEXT: Type = 3;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod KittyGraphicsPlacementIteratorOption {
    pub type Type = ::std::os::raw::c_int;
    pub const LAYER: Type = 0;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod KittyImageFormat {
    pub type Type = ::std::os::raw::c_int;
    pub const RGB: Type = 0;
    pub const RGBA: Type = 1;
    pub const PNG: Type = 2;
    pub const GRAY_ALPHA: Type = 3;
    pub const GRAY: Type = 4;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod KittyImageCompression {
    pub type Type = ::std::os::raw::c_int;
    pub const NONE: Type = 0;
    pub const ZLIB_DEFLATE: Type = 1;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod KittyGraphicsImageData {
    pub type Type = ::std::os::raw::c_int;
    pub const INVALID: Type = 0;
    pub const ID: Type = 1;
    pub const NUMBER: Type = 2;
    pub const WIDTH: Type = 3;
    pub const HEIGHT: Type = 4;
    pub const FORMAT: Type = 5;
    pub const COMPRESSION: Type = 6;
    pub const DATA_PTR: Type = 7;
    pub const DATA_LEN: Type = 8;
    pub const GENERATION: Type = 9;
    pub const MAX_VALUE: Type = 2147483647;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct KittyGraphicsPlacementRenderInfo {
    pub size: usize,
    pub pixel_width: u32,
    pub pixel_height: u32,
    pub grid_cols: u32,
    pub grid_rows: u32,
    pub viewport_col: i32,
    pub viewport_row: i32,
    pub viewport_visible: bool,
    pub source_x: u32,
    pub source_y: u32,
    pub source_width: u32,
    pub source_height: u32,
}
unsafe extern "C" {
    pub fn ghostty_kitty_graphics_get(
        graphics: KittyGraphics,
        data: KittyGraphicsData::Type,
        out: *mut ::std::os::raw::c_void,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_kitty_graphics_image(
        graphics: KittyGraphics,
        image_id: u32,
    ) -> KittyGraphicsImage;
}
unsafe extern "C" {
    pub fn ghostty_kitty_graphics_image_get(
        image: KittyGraphicsImage,
        data: KittyGraphicsImageData::Type,
        out: *mut ::std::os::raw::c_void,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_kitty_graphics_image_get_multi(
        image: KittyGraphicsImage,
        count: usize,
        keys: *const KittyGraphicsImageData::Type,
        values: *mut *mut ::std::os::raw::c_void,
        out_written: *mut usize,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_kitty_graphics_placement_iterator_new(
        allocator: *const Allocator,
        out_iterator: *mut KittyGraphicsPlacementIterator,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_kitty_graphics_placement_iterator_free(iterator: KittyGraphicsPlacementIterator);
}
unsafe extern "C" {
    pub fn ghostty_kitty_graphics_placement_iterator_set(
        iterator: KittyGraphicsPlacementIterator,
        option: KittyGraphicsPlacementIteratorOption::Type,
        value: *const ::std::os::raw::c_void,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_kitty_graphics_placement_next(iterator: KittyGraphicsPlacementIterator) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_kitty_graphics_placement_get(
        iterator: KittyGraphicsPlacementIterator,
        data: KittyGraphicsPlacementData::Type,
        out: *mut ::std::os::raw::c_void,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_kitty_graphics_placement_get_multi(
        iterator: KittyGraphicsPlacementIterator,
        count: usize,
        keys: *const KittyGraphicsPlacementData::Type,
        values: *mut *mut ::std::os::raw::c_void,
        out_written: *mut usize,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_kitty_graphics_placement_rect(
        iterator: KittyGraphicsPlacementIterator,
        image: KittyGraphicsImage,
        terminal: Terminal,
        out_selection: *mut Selection,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_kitty_graphics_placement_pixel_size(
        iterator: KittyGraphicsPlacementIterator,
        image: KittyGraphicsImage,
        terminal: Terminal,
        out_width: *mut u32,
        out_height: *mut u32,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_kitty_graphics_placement_grid_size(
        iterator: KittyGraphicsPlacementIterator,
        image: KittyGraphicsImage,
        terminal: Terminal,
        out_cols: *mut u32,
        out_rows: *mut u32,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_kitty_graphics_placement_viewport_pos(
        iterator: KittyGraphicsPlacementIterator,
        image: KittyGraphicsImage,
        terminal: Terminal,
        out_col: *mut i32,
        out_row: *mut i32,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_kitty_graphics_placement_source_rect(
        iterator: KittyGraphicsPlacementIterator,
        image: KittyGraphicsImage,
        out_x: *mut u32,
        out_y: *mut u32,
        out_width: *mut u32,
        out_height: *mut u32,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_kitty_graphics_placement_render_info(
        iterator: KittyGraphicsPlacementIterator,
        image: KittyGraphicsImage,
        terminal: Terminal,
        out_info: *mut KittyGraphicsPlacementRenderInfo,
    ) -> Result::Type;
}
pub mod TerminalCompressionMode {
    pub type Type = ::std::os::raw::c_int;
    pub const INCREMENTAL: Type = 0;
    pub const FULL: Type = 1;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod TerminalCompressionResult {
    pub type Type = ::std::os::raw::c_int;
    pub const UNSUPPORTED: Type = 0;
    pub const PENDING: Type = 1;
    pub const COMPLETE: Type = 2;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod TerminalScrollViewportTag {
    pub type Type = ::std::os::raw::c_int;
    pub const TOP: Type = 0;
    pub const BOTTOM: Type = 1;
    pub const DELTA: Type = 2;
    pub const ROW: Type = 3;
    pub const MAX_VALUE: Type = 2147483647;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union TerminalScrollViewportValue {
    pub delta: isize,
    pub row: usize,
    pub _padding: [u64; 2usize],
}
impl Default for TerminalScrollViewportValue {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct TerminalScrollViewport {
    pub tag: TerminalScrollViewportTag::Type,
    pub value: TerminalScrollViewportValue,
}
impl Default for TerminalScrollViewport {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub mod TerminalScreen {
    pub type Type = ::std::os::raw::c_int;
    pub const PRIMARY: Type = 0;
    pub const ALTERNATE: Type = 1;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod TerminalCursorStyle {
    pub type Type = ::std::os::raw::c_int;
    pub const BAR: Type = 0;
    pub const BLOCK: Type = 1;
    pub const UNDERLINE: Type = 2;
    pub const BLOCK_HOLLOW: Type = 3;
    pub const MAX_VALUE: Type = 2147483647;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct TerminalScrollbar {
    pub total: u64,
    pub offset: u64,
    pub len: u64,
}
pub type TerminalBellFn = ::std::option::Option<
    unsafe extern "C" fn(terminal: Terminal, userdata: *mut ::std::os::raw::c_void),
>;
pub mod TerminalUnknownSequenceTag {
    pub type Type = ::std::os::raw::c_int;
    pub const GHOSTTY_TERMINAL_UNKNOWN_SEQUENCE_APC: Type = 0;
    pub const GHOSTTY_TERMINAL_UNKNOWN_SEQUENCE_MAX_VALUE: Type = 2147483647;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TerminalUnknownStringSequence {
    pub truncated: bool,
    pub content: String,
}
impl Default for TerminalUnknownStringSequence {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union TerminalUnknownSequenceValue {
    pub apc: TerminalUnknownStringSequence,
    pub _padding: [u64; 16usize],
}
impl Default for TerminalUnknownSequenceValue {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct TerminalUnknownSequence {
    pub tag: TerminalUnknownSequenceTag::Type,
    pub value: TerminalUnknownSequenceValue,
}
impl Default for TerminalUnknownSequence {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type TerminalUnknownSequenceFn = ::std::option::Option<
    unsafe extern "C" fn(
        terminal: Terminal,
        userdata: *mut ::std::os::raw::c_void,
        sequence: *const TerminalUnknownSequence,
    ),
>;
pub mod ClipboardLocation {
    pub type Type = ::std::os::raw::c_int;
    pub const STANDARD: Type = 0;
    pub const SELECTION: Type = 1;
    pub const PRIMARY: Type = 2;
    pub const MAX_VALUE: Type = 2147483647;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ClipboardContent {
    pub mime: String,
    pub data: String,
}
impl Default for ClipboardContent {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ClipboardWrite {
    pub size: usize,
    pub location: ClipboardLocation::Type,
    pub contents: *const ClipboardContent,
    pub contents_len: usize,
}
impl Default for ClipboardWrite {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub mod ClipboardWriteResult {
    pub type Type = ::std::os::raw::c_int;
    pub const SUCCESS: Type = 0;
    pub const DENIED: Type = 1;
    pub const UNSUPPORTED: Type = 2;
    pub const BUSY: Type = 3;
    pub const INVALID_DATA: Type = 4;
    pub const IO_ERROR: Type = 5;
    pub const MAX_VALUE: Type = 2147483647;
}
pub type TerminalClipboardWriteFn = ::std::option::Option<
    unsafe extern "C" fn(
        terminal: Terminal,
        userdata: *mut ::std::os::raw::c_void,
        write: *const ClipboardWrite,
    ) -> ClipboardWriteResult::Type,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TerminalDesktopNotification {
    pub size: usize,
    pub title: String,
    pub body: String,
}
impl Default for TerminalDesktopNotification {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type TerminalDesktopNotificationFn = ::std::option::Option<
    unsafe extern "C" fn(
        terminal: Terminal,
        userdata: *mut ::std::os::raw::c_void,
        notification: *const TerminalDesktopNotification,
    ),
>;
pub mod TerminalProgressState {
    pub type Type = ::std::os::raw::c_int;
    pub const REMOVE: Type = 0;
    pub const SET: Type = 1;
    pub const ERROR: Type = 2;
    pub const INDETERMINATE: Type = 3;
    pub const PAUSE: Type = 4;
    pub const MAX_VALUE: Type = 2147483647;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TerminalProgressReport {
    pub size: usize,
    pub state: TerminalProgressState::Type,
    pub progress: i8,
}
impl Default for TerminalProgressReport {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type TerminalProgressReportFn = ::std::option::Option<
    unsafe extern "C" fn(
        terminal: Terminal,
        userdata: *mut ::std::os::raw::c_void,
        report: *const TerminalProgressReport,
    ),
>;
pub type TerminalColorSchemeFn = ::std::option::Option<
    unsafe extern "C" fn(
        terminal: Terminal,
        userdata: *mut ::std::os::raw::c_void,
        out_scheme: *mut ColorScheme::Type,
    ) -> bool,
>;
pub type TerminalDeviceAttributesFn = ::std::option::Option<
    unsafe extern "C" fn(
        terminal: Terminal,
        userdata: *mut ::std::os::raw::c_void,
        out_attrs: *mut DeviceAttributes,
    ) -> bool,
>;
pub type TerminalEnquiryFn = ::std::option::Option<
    unsafe extern "C" fn(terminal: Terminal, userdata: *mut ::std::os::raw::c_void) -> String,
>;
pub type TerminalSizeFn = ::std::option::Option<
    unsafe extern "C" fn(
        terminal: Terminal,
        userdata: *mut ::std::os::raw::c_void,
        out_size: *mut SizeReportSize,
    ) -> bool,
>;
pub type TerminalTitleChangedFn = ::std::option::Option<
    unsafe extern "C" fn(terminal: Terminal, userdata: *mut ::std::os::raw::c_void),
>;
pub type TerminalPwdChangedFn = ::std::option::Option<
    unsafe extern "C" fn(terminal: Terminal, userdata: *mut ::std::os::raw::c_void),
>;
pub type TerminalWritePtyFn = ::std::option::Option<
    unsafe extern "C" fn(
        terminal: Terminal,
        userdata: *mut ::std::os::raw::c_void,
        data: *const u8,
        len: usize,
    ),
>;
pub type TerminalXtversionFn = ::std::option::Option<
    unsafe extern "C" fn(terminal: Terminal, userdata: *mut ::std::os::raw::c_void) -> String,
>;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct TerminalModeConfig {
    pub mode: Mode,
    pub value: bool,
}
pub mod TerminalOption {
    pub type Type = ::std::os::raw::c_int;
    pub const USERDATA: Type = 0;
    pub const WRITE_PTY: Type = 1;
    pub const BELL: Type = 2;
    pub const ENQUIRY: Type = 3;
    pub const XTVERSION: Type = 4;
    pub const TITLE_CHANGED: Type = 5;
    pub const SIZE: Type = 6;
    pub const COLOR_SCHEME: Type = 7;
    pub const DEVICE_ATTRIBUTES: Type = 8;
    pub const TITLE: Type = 9;
    pub const PWD: Type = 10;
    pub const COLOR_FOREGROUND: Type = 11;
    pub const COLOR_BACKGROUND: Type = 12;
    pub const COLOR_CURSOR: Type = 13;
    pub const COLOR_PALETTE: Type = 14;
    pub const KITTY_IMAGE_STORAGE_LIMIT: Type = 15;
    pub const KITTY_IMAGE_MEDIUM_FILE: Type = 16;
    pub const KITTY_IMAGE_MEDIUM_TEMP_FILE: Type = 17;
    pub const KITTY_IMAGE_MEDIUM_SHARED_MEM: Type = 18;
    pub const APC_MAX_BYTES: Type = 19;
    pub const APC_MAX_BYTES_KITTY: Type = 20;
    pub const SELECTION: Type = 21;
    pub const DEFAULT_CURSOR_STYLE: Type = 22;
    pub const DEFAULT_CURSOR_BLINK: Type = 23;
    pub const GLYPH_PROTOCOL: Type = 24;
    pub const PWD_CHANGED: Type = 25;
    pub const CLIPBOARD_WRITE: Type = 26;
    pub const SCROLLBACK_MAX_BYTES: Type = 27;
    pub const SCROLLBACK_MAX_LINES: Type = 28;
    pub const DESKTOP_NOTIFICATION: Type = 29;
    pub const PROGRESS_REPORT: Type = 30;
    pub const CONTINUATION_MAX_BYTES: Type = 31;
    pub const TITLE_REPORT: Type = 32;
    pub const MODE_DEFAULT: Type = 33;
    pub const MODE: Type = 34;
    pub const UNKNOWN_SEQUENCE: Type = 35;
    pub const UNKNOWN_MAX_BYTES: Type = 36;
    pub const TERMINFO_NAME: Type = 37;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod TerminalData {
    pub type Type = ::std::os::raw::c_int;
    pub const INVALID: Type = 0;
    pub const COLS: Type = 1;
    pub const ROWS: Type = 2;
    pub const CURSOR_X: Type = 3;
    pub const CURSOR_Y: Type = 4;
    pub const CURSOR_PENDING_WRAP: Type = 5;
    pub const ACTIVE_SCREEN: Type = 6;
    pub const CURSOR_VISIBLE: Type = 7;
    pub const KITTY_KEYBOARD_FLAGS: Type = 8;
    pub const SCROLLBAR: Type = 9;
    pub const CURSOR_STYLE: Type = 10;
    pub const MOUSE_TRACKING: Type = 11;
    pub const TITLE: Type = 12;
    pub const PWD: Type = 13;
    pub const TOTAL_ROWS: Type = 14;
    pub const SCROLLBACK_ROWS: Type = 15;
    pub const WIDTH_PX: Type = 16;
    pub const HEIGHT_PX: Type = 17;
    pub const COLOR_FOREGROUND: Type = 18;
    pub const COLOR_BACKGROUND: Type = 19;
    pub const COLOR_CURSOR: Type = 20;
    pub const COLOR_PALETTE: Type = 21;
    pub const COLOR_FOREGROUND_DEFAULT: Type = 22;
    pub const COLOR_BACKGROUND_DEFAULT: Type = 23;
    pub const COLOR_CURSOR_DEFAULT: Type = 24;
    pub const COLOR_PALETTE_DEFAULT: Type = 25;
    pub const KITTY_IMAGE_STORAGE_LIMIT: Type = 26;
    pub const KITTY_IMAGE_MEDIUM_FILE: Type = 27;
    pub const KITTY_IMAGE_MEDIUM_TEMP_FILE: Type = 28;
    pub const KITTY_IMAGE_MEDIUM_SHARED_MEM: Type = 29;
    pub const KITTY_GRAPHICS: Type = 30;
    pub const SELECTION: Type = 31;
    pub const VIEWPORT_ACTIVE: Type = 32;
    pub const VT_PROCESSING_ERROR: Type = 33;
    pub const SCROLLBACK_MAX_BYTES: Type = 34;
    pub const SCROLLBACK_MAX_LINES: Type = 35;
    pub const CONTINUATION_MAX_BYTES: Type = 36;
    pub const MODE: Type = 37;
    pub const VT_GROUND: Type = 38;
    pub const CURSOR_AT_PROMPT: Type = 39;
    pub const MAX_VALUE: Type = 2147483647;
}
unsafe extern "C" {
    pub fn ghostty_terminal_new(
        allocator: *const Allocator,
        terminal: *mut Terminal,
        cols: u16,
        rows: u16,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_free(terminal: Terminal);
}
unsafe extern "C" {
    pub fn ghostty_terminal_reset(terminal: Terminal);
}
unsafe extern "C" {
    pub fn ghostty_terminal_resize(
        terminal: Terminal,
        cols: u16,
        rows: u16,
        cell_width_px: u32,
        cell_height_px: u32,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_set(
        terminal: Terminal,
        option: TerminalOption::Type,
        value: *const ::std::os::raw::c_void,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_vt_write(terminal: Terminal, data: *const u8, len: usize);
}
unsafe extern "C" {
    pub fn ghostty_terminal_vt_write_until_ground(
        terminal: Terminal,
        data: *const u8,
        len: usize,
        out_consumed: *mut usize,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_continuation_write(terminal: Terminal, writer: Writer) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_continuation_buf(
        terminal: Terminal,
        buf: *mut u8,
        buf_len: usize,
        out_written: *mut usize,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_continuation_alloc(
        terminal: Terminal,
        allocator: *const Allocator,
        out_ptr: *mut *mut u8,
        out_len: *mut usize,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_scroll_viewport(terminal: Terminal, behavior: TerminalScrollViewport);
}
unsafe extern "C" {
    pub fn ghostty_terminal_compression_activity(
        terminal: Terminal,
        out_activity: *mut u64,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_compress(
        terminal: Terminal,
        mode: TerminalCompressionMode::Type,
        out_result: *mut TerminalCompressionResult::Type,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_get(
        terminal: Terminal,
        data: TerminalData::Type,
        out: *mut ::std::os::raw::c_void,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_get_multi(
        terminal: Terminal,
        count: usize,
        keys: *const TerminalData::Type,
        values: *mut *mut ::std::os::raw::c_void,
        out_written: *mut usize,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_grid_ref(
        terminal: Terminal,
        point: Point,
        out_ref: *mut GridRef,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_grid_ref_track(
        terminal: Terminal,
        point: Point,
        out_ref: *mut TrackedGridRef,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_terminal_point_from_grid_ref(
        terminal: Terminal,
        ref_: *const GridRef,
        tag: PointTag::Type,
        out: *mut PointCoordinate,
    ) -> Result::Type;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct FormatterScreenExtra {
    pub size: usize,
    pub cursor: bool,
    pub style: bool,
    pub hyperlink: bool,
    pub protection: bool,
    pub kitty_keyboard: bool,
    pub charsets: bool,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct FormatterTerminalExtra {
    pub size: usize,
    pub palette: bool,
    pub modes: bool,
    pub scrolling_region: bool,
    pub tabstops: bool,
    pub pwd: bool,
    pub keyboard: bool,
    pub screen: FormatterScreenExtra,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FormatterTerminalOptions {
    pub size: usize,
    pub emit: FormatterFormat::Type,
    pub unwrap: bool,
    pub trim: bool,
    pub extra: FormatterTerminalExtra,
    pub selection: *const Selection,
}
impl Default for FormatterTerminalOptions {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn ghostty_formatter_terminal_new(
        allocator: *const Allocator,
        formatter: *mut Formatter,
        terminal: Terminal,
        options: FormatterTerminalOptions,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_formatter_format(formatter: Formatter, writer: Writer) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_formatter_format_buf(
        formatter: Formatter,
        buf: *mut u8,
        buf_len: usize,
        out_written: *mut usize,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_formatter_format_alloc(
        formatter: Formatter,
        allocator: *const Allocator,
        out_ptr: *mut *mut u8,
        out_len: *mut usize,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_formatter_free(formatter: Formatter);
}
pub mod RenderStateDirty {
    pub type Type = ::std::os::raw::c_int;
    pub const FALSE: Type = 0;
    pub const PARTIAL: Type = 1;
    pub const FULL: Type = 2;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod RenderStateCursorVisualStyle {
    pub type Type = ::std::os::raw::c_int;
    pub const BAR: Type = 0;
    pub const BLOCK: Type = 1;
    pub const UNDERLINE: Type = 2;
    pub const BLOCK_HOLLOW: Type = 3;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod RenderStateData {
    pub type Type = ::std::os::raw::c_int;
    pub const INVALID: Type = 0;
    pub const COLS: Type = 1;
    pub const ROWS: Type = 2;
    pub const DIRTY: Type = 3;
    pub const ROW_ITERATOR: Type = 4;
    pub const COLOR_BACKGROUND: Type = 5;
    pub const COLOR_FOREGROUND: Type = 6;
    pub const COLOR_CURSOR: Type = 7;
    pub const COLOR_CURSOR_HAS_VALUE: Type = 8;
    pub const COLOR_PALETTE: Type = 9;
    pub const CURSOR_VISUAL_STYLE: Type = 10;
    pub const CURSOR_VISIBLE: Type = 11;
    pub const CURSOR_BLINKING: Type = 12;
    pub const CURSOR_PASSWORD_INPUT: Type = 13;
    pub const CURSOR_VIEWPORT_HAS_VALUE: Type = 14;
    pub const CURSOR_VIEWPORT_X: Type = 15;
    pub const CURSOR_VIEWPORT_Y: Type = 16;
    pub const CURSOR_VIEWPORT_WIDE_TAIL: Type = 17;
    pub const CURSOR: Type = 18;
    pub const COLORS: Type = 19;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod RenderStateOption {
    pub type Type = ::std::os::raw::c_int;
    pub const DIRTY: Type = 0;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod RenderStateRowData {
    pub type Type = ::std::os::raw::c_int;
    pub const INVALID: Type = 0;
    pub const DIRTY: Type = 1;
    pub const RAW: Type = 2;
    pub const CELLS: Type = 3;
    pub const SELECTION: Type = 4;
    pub const CELLS_RAW: Type = 5;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod RenderStateRowOption {
    pub type Type = ::std::os::raw::c_int;
    pub const DIRTY: Type = 0;
    pub const MAX_VALUE: Type = 2147483647;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct RenderStateRowSelection {
    pub size: usize,
    pub start_x: u16,
    pub end_x: u16,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RenderStateCursor {
    pub size: usize,
    pub viewport_has_value: bool,
    pub viewport_x: u16,
    pub viewport_y: u16,
    pub wide_tail: bool,
    pub visible: bool,
    pub blinking: bool,
    pub password_input: bool,
    pub visual_style: RenderStateCursorVisualStyle::Type,
}
impl Default for RenderStateCursor {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RenderStateColors {
    pub size: usize,
    pub background: ColorRgb,
    pub foreground: ColorRgb,
    pub cursor: ColorRgb,
    pub cursor_has_value: bool,
    pub palette: [ColorRgb; 256usize],
}
impl Default for RenderStateColors {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn ghostty_render_state_new(
        allocator: *const Allocator,
        state: *mut RenderState,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_render_state_free(state: RenderState);
}
unsafe extern "C" {
    pub fn ghostty_render_state_update(state: RenderState, terminal: Terminal) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_render_state_begin_update(
        state: RenderState,
        terminal: Terminal,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_render_state_end_update(state: RenderState) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_render_state_clean(state: RenderState) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_render_state_get(
        state: RenderState,
        data: RenderStateData::Type,
        out: *mut ::std::os::raw::c_void,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_render_state_get_multi(
        state: RenderState,
        count: usize,
        keys: *const RenderStateData::Type,
        values: *mut *mut ::std::os::raw::c_void,
        out_written: *mut usize,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_render_state_set(
        state: RenderState,
        option: RenderStateOption::Type,
        value: *const ::std::os::raw::c_void,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_render_state_row_iterator_new(
        allocator: *const Allocator,
        out_iterator: *mut RenderStateRowIterator,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_render_state_row_iterator_free(iterator: RenderStateRowIterator);
}
unsafe extern "C" {
    pub fn ghostty_render_state_row_iterator_next(iterator: RenderStateRowIterator) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_render_state_row_iterator_next_dirty(
        iterator: RenderStateRowIterator,
        out_y: *mut u16,
    ) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_render_state_row_get(
        iterator: RenderStateRowIterator,
        data: RenderStateRowData::Type,
        out: *mut ::std::os::raw::c_void,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_render_state_row_get_multi(
        iterator: RenderStateRowIterator,
        count: usize,
        keys: *const RenderStateRowData::Type,
        values: *mut *mut ::std::os::raw::c_void,
        out_written: *mut usize,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_render_state_row_set(
        iterator: RenderStateRowIterator,
        option: RenderStateRowOption::Type,
        value: *const ::std::os::raw::c_void,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_render_state_row_cells_new(
        allocator: *const Allocator,
        out_cells: *mut RenderStateRowCells,
    ) -> Result::Type;
}
pub mod RenderStateRowCellsData {
    pub type Type = ::std::os::raw::c_int;
    pub const INVALID: Type = 0;
    pub const RAW: Type = 1;
    pub const STYLE: Type = 2;
    pub const GRAPHEMES_LEN: Type = 3;
    pub const GRAPHEMES_BUF: Type = 4;
    pub const BG_COLOR: Type = 5;
    pub const FG_COLOR: Type = 6;
    pub const SELECTED: Type = 7;
    pub const HAS_STYLING: Type = 8;
    pub const GRAPHEMES_UTF8: Type = 9;
    pub const MAX_VALUE: Type = 2147483647;
}
unsafe extern "C" {
    pub fn ghostty_render_state_row_cells_next(cells: RenderStateRowCells) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_render_state_row_cells_select(
        cells: RenderStateRowCells,
        x: u16,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_render_state_row_cells_get(
        cells: RenderStateRowCells,
        data: RenderStateRowCellsData::Type,
        out: *mut ::std::os::raw::c_void,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_render_state_row_cells_get_multi(
        cells: RenderStateRowCells,
        count: usize,
        keys: *const RenderStateRowCellsData::Type,
        values: *mut *mut ::std::os::raw::c_void,
        out_written: *mut usize,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_render_state_row_cells_free(cells: RenderStateRowCells);
}
unsafe extern "C" {
    pub fn ghostty_tracked_grid_ref_free(ref_: TrackedGridRef);
}
unsafe extern "C" {
    pub fn ghostty_tracked_grid_ref_has_value(ref_: TrackedGridRef) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_tracked_grid_ref_point(
        ref_: TrackedGridRef,
        tag: PointTag::Type,
        out_point: *mut PointCoordinate,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_tracked_grid_ref_set(
        ref_: TrackedGridRef,
        terminal: Terminal,
        point: Point,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_tracked_grid_ref_snapshot(
        ref_: TrackedGridRef,
        out_ref: *mut GridRef,
    ) -> Result::Type;
}
pub mod OscCommandType {
    pub type Type = ::std::os::raw::c_int;
    pub const INVALID: Type = 0;
    pub const CHANGE_WINDOW_TITLE: Type = 1;
    pub const CHANGE_WINDOW_ICON: Type = 2;
    pub const SEMANTIC_PROMPT: Type = 3;
    pub const CLIPBOARD_CONTENTS: Type = 4;
    pub const REPORT_PWD: Type = 5;
    pub const MOUSE_SHAPE: Type = 6;
    pub const COLOR_OPERATION: Type = 7;
    pub const KITTY_COLOR_PROTOCOL: Type = 8;
    pub const SHOW_DESKTOP_NOTIFICATION: Type = 9;
    pub const HYPERLINK_START: Type = 10;
    pub const HYPERLINK_END: Type = 11;
    pub const CONEMU_SLEEP: Type = 12;
    pub const CONEMU_SHOW_MESSAGE_BOX: Type = 13;
    pub const CONEMU_CHANGE_TAB_TITLE: Type = 14;
    pub const CONEMU_PROGRESS_REPORT: Type = 15;
    pub const CONEMU_WAIT_INPUT: Type = 16;
    pub const CONEMU_GUIMACRO: Type = 17;
    pub const CONEMU_RUN_PROCESS: Type = 18;
    pub const CONEMU_OUTPUT_ENVIRONMENT_VARIABLE: Type = 19;
    pub const CONEMU_XTERM_EMULATION: Type = 20;
    pub const CONEMU_COMMENT: Type = 21;
    pub const KITTY_TEXT_SIZING: Type = 22;
    pub const KITTY_CLIPBOARD_PROTOCOL: Type = 23;
    pub const KITTY_DND_PROTOCOL: Type = 24;
    pub const CONTEXT_SIGNAL: Type = 25;
    pub const TYPE_MAX_VALUE: Type = 2147483647;
}
pub mod OscCommandData {
    pub type Type = ::std::os::raw::c_int;
    pub const INVALID: Type = 0;
    pub const CHANGE_WINDOW_TITLE_STR: Type = 1;
    pub const MAX_VALUE: Type = 2147483647;
}
unsafe extern "C" {
    pub fn ghostty_osc_new(allocator: *const Allocator, parser: *mut OscParser) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_osc_free(parser: OscParser);
}
unsafe extern "C" {
    pub fn ghostty_osc_reset(parser: OscParser);
}
unsafe extern "C" {
    pub fn ghostty_osc_next(parser: OscParser, byte: u8);
}
unsafe extern "C" {
    pub fn ghostty_osc_end(parser: OscParser, terminator: u8) -> OscCommand;
}
unsafe extern "C" {
    pub fn ghostty_osc_command_type(command: OscCommand) -> OscCommandType::Type;
}
unsafe extern "C" {
    pub fn ghostty_osc_command_data(
        command: OscCommand,
        data: OscCommandData::Type,
        out: *mut ::std::os::raw::c_void,
    ) -> bool;
}
pub mod SgrAttributeTag {
    pub type Type = ::std::os::raw::c_int;
    pub const UNSET: Type = 0;
    pub const UNKNOWN: Type = 1;
    pub const BOLD: Type = 2;
    pub const RESET_BOLD: Type = 3;
    pub const ITALIC: Type = 4;
    pub const RESET_ITALIC: Type = 5;
    pub const FAINT: Type = 6;
    pub const UNDERLINE: Type = 7;
    pub const UNDERLINE_COLOR: Type = 8;
    pub const UNDERLINE_COLOR_256: Type = 9;
    pub const RESET_UNDERLINE_COLOR: Type = 10;
    pub const OVERLINE: Type = 11;
    pub const RESET_OVERLINE: Type = 12;
    pub const BLINK: Type = 13;
    pub const RESET_BLINK: Type = 14;
    pub const INVERSE: Type = 15;
    pub const RESET_INVERSE: Type = 16;
    pub const INVISIBLE: Type = 17;
    pub const RESET_INVISIBLE: Type = 18;
    pub const STRIKETHROUGH: Type = 19;
    pub const RESET_STRIKETHROUGH: Type = 20;
    pub const DIRECT_COLOR_FG: Type = 21;
    pub const DIRECT_COLOR_BG: Type = 22;
    pub const BG_8: Type = 23;
    pub const FG_8: Type = 24;
    pub const RESET_FG: Type = 25;
    pub const RESET_BG: Type = 26;
    pub const BRIGHT_BG_8: Type = 27;
    pub const BRIGHT_FG_8: Type = 28;
    pub const BG_256: Type = 29;
    pub const FG_256: Type = 30;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod SgrUnderline {
    pub type Type = ::std::os::raw::c_int;
    pub const NONE: Type = 0;
    pub const SINGLE: Type = 1;
    pub const DOUBLE: Type = 2;
    pub const CURLY: Type = 3;
    pub const DOTTED: Type = 4;
    pub const DASHED: Type = 5;
    pub const MAX_VALUE: Type = 2147483647;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SgrUnknown {
    pub full_ptr: *const u16,
    pub full_len: usize,
    pub partial_ptr: *const u16,
    pub partial_len: usize,
}
impl Default for SgrUnknown {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union SgrAttributeValue {
    pub unknown: SgrUnknown,
    pub underline: SgrUnderline::Type,
    pub underline_color: ColorRgb,
    pub underline_color_256: ColorPaletteIndex,
    pub direct_color_fg: ColorRgb,
    pub direct_color_bg: ColorRgb,
    pub bg_8: ColorPaletteIndex,
    pub fg_8: ColorPaletteIndex,
    pub bright_bg_8: ColorPaletteIndex,
    pub bright_fg_8: ColorPaletteIndex,
    pub bg_256: ColorPaletteIndex,
    pub fg_256: ColorPaletteIndex,
    pub _padding: [u64; 8usize],
}
impl Default for SgrAttributeValue {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct SgrAttribute {
    pub tag: SgrAttributeTag::Type,
    pub value: SgrAttributeValue,
}
impl Default for SgrAttribute {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn ghostty_sgr_new(allocator: *const Allocator, parser: *mut SgrParser) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_sgr_free(parser: SgrParser);
}
unsafe extern "C" {
    pub fn ghostty_sgr_reset(parser: SgrParser);
}
unsafe extern "C" {
    pub fn ghostty_sgr_set_params(
        parser: SgrParser,
        params: *const u16,
        separators: *const ::std::os::raw::c_char,
        len: usize,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_sgr_next(parser: SgrParser, attr: *mut SgrAttribute) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_sgr_unknown_full(unknown: SgrUnknown, ptr: *mut *const u16) -> usize;
}
unsafe extern "C" {
    pub fn ghostty_sgr_unknown_partial(unknown: SgrUnknown, ptr: *mut *const u16) -> usize;
}
unsafe extern "C" {
    pub fn ghostty_sgr_attribute_tag(attr: SgrAttribute) -> SgrAttributeTag::Type;
}
unsafe extern "C" {
    pub fn ghostty_sgr_attribute_value(attr: *mut SgrAttribute) -> *mut SgrAttributeValue;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SysImage {
    pub width: u32,
    pub height: u32,
    pub data: *mut u8,
    pub data_len: usize,
}
impl Default for SysImage {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub mod SysLogLevel {
    pub type Type = ::std::os::raw::c_int;
    pub const ERROR: Type = 0;
    pub const WARNING: Type = 1;
    pub const INFO: Type = 2;
    pub const DEBUG: Type = 3;
    pub const MAX_VALUE: Type = 2147483647;
}
pub type SysLogFn = ::std::option::Option<
    unsafe extern "C" fn(
        userdata: *mut ::std::os::raw::c_void,
        level: SysLogLevel::Type,
        scope: *const u8,
        scope_len: usize,
        message: *const u8,
        message_len: usize,
    ),
>;
pub type SysDecodePngFn = ::std::option::Option<
    unsafe extern "C" fn(
        userdata: *mut ::std::os::raw::c_void,
        allocator: *const Allocator,
        data: *const u8,
        data_len: usize,
        out: *mut SysImage,
    ) -> bool,
>;
pub mod SysOption {
    pub type Type = ::std::os::raw::c_int;
    pub const GHOSTTY_SYS_OPT_USERDATA: Type = 0;
    pub const GHOSTTY_SYS_OPT_DECODE_PNG: Type = 1;
    pub const GHOSTTY_SYS_OPT_LOG: Type = 2;
    pub const GHOSTTY_SYS_OPT_MAX_VALUE: Type = 2147483647;
}
unsafe extern "C" {
    pub fn ghostty_sys_set(
        option: SysOption::Type,
        value: *const ::std::os::raw::c_void,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_sys_log_stderr(
        userdata: *mut ::std::os::raw::c_void,
        level: SysLogLevel::Type,
        scope: *const u8,
        scope_len: usize,
        message: *const u8,
        message_len: usize,
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KeyEventImpl {
    _unused: [u8; 0],
}
pub type KeyEvent = *mut KeyEventImpl;
pub mod KeyAction {
    pub type Type = ::std::os::raw::c_int;
    pub const RELEASE: Type = 0;
    pub const PRESS: Type = 1;
    pub const REPEAT: Type = 2;
    pub const MAX_VALUE: Type = 2147483647;
}
pub type Mods = u16;
pub mod Key {
    pub type Type = ::std::os::raw::c_int;
    pub const UNIDENTIFIED: Type = 0;
    pub const BACKQUOTE: Type = 1;
    pub const BACKSLASH: Type = 2;
    pub const BRACKET_LEFT: Type = 3;
    pub const BRACKET_RIGHT: Type = 4;
    pub const COMMA: Type = 5;
    pub const DIGIT_0: Type = 6;
    pub const DIGIT_1: Type = 7;
    pub const DIGIT_2: Type = 8;
    pub const DIGIT_3: Type = 9;
    pub const DIGIT_4: Type = 10;
    pub const DIGIT_5: Type = 11;
    pub const DIGIT_6: Type = 12;
    pub const DIGIT_7: Type = 13;
    pub const DIGIT_8: Type = 14;
    pub const DIGIT_9: Type = 15;
    pub const EQUAL: Type = 16;
    pub const INTL_BACKSLASH: Type = 17;
    pub const INTL_RO: Type = 18;
    pub const INTL_YEN: Type = 19;
    pub const A: Type = 20;
    pub const B: Type = 21;
    pub const C: Type = 22;
    pub const D: Type = 23;
    pub const E: Type = 24;
    pub const F: Type = 25;
    pub const G: Type = 26;
    pub const H: Type = 27;
    pub const I: Type = 28;
    pub const J: Type = 29;
    pub const K: Type = 30;
    pub const L: Type = 31;
    pub const M: Type = 32;
    pub const N: Type = 33;
    pub const O: Type = 34;
    pub const P: Type = 35;
    pub const Q: Type = 36;
    pub const R: Type = 37;
    pub const S: Type = 38;
    pub const T: Type = 39;
    pub const U: Type = 40;
    pub const V: Type = 41;
    pub const W: Type = 42;
    pub const X: Type = 43;
    pub const Y: Type = 44;
    pub const Z: Type = 45;
    pub const MINUS: Type = 46;
    pub const PERIOD: Type = 47;
    pub const QUOTE: Type = 48;
    pub const SEMICOLON: Type = 49;
    pub const SLASH: Type = 50;
    pub const ALT_LEFT: Type = 51;
    pub const ALT_RIGHT: Type = 52;
    pub const BACKSPACE: Type = 53;
    pub const CAPS_LOCK: Type = 54;
    pub const CONTEXT_MENU: Type = 55;
    pub const CONTROL_LEFT: Type = 56;
    pub const CONTROL_RIGHT: Type = 57;
    pub const ENTER: Type = 58;
    pub const META_LEFT: Type = 59;
    pub const META_RIGHT: Type = 60;
    pub const SHIFT_LEFT: Type = 61;
    pub const SHIFT_RIGHT: Type = 62;
    pub const SPACE: Type = 63;
    pub const TAB: Type = 64;
    pub const CONVERT: Type = 65;
    pub const KANA_MODE: Type = 66;
    pub const NON_CONVERT: Type = 67;
    pub const DELETE: Type = 68;
    pub const END: Type = 69;
    pub const HELP: Type = 70;
    pub const HOME: Type = 71;
    pub const INSERT: Type = 72;
    pub const PAGE_DOWN: Type = 73;
    pub const PAGE_UP: Type = 74;
    pub const ARROW_DOWN: Type = 75;
    pub const ARROW_LEFT: Type = 76;
    pub const ARROW_RIGHT: Type = 77;
    pub const ARROW_UP: Type = 78;
    pub const NUM_LOCK: Type = 79;
    pub const NUMPAD_0: Type = 80;
    pub const NUMPAD_1: Type = 81;
    pub const NUMPAD_2: Type = 82;
    pub const NUMPAD_3: Type = 83;
    pub const NUMPAD_4: Type = 84;
    pub const NUMPAD_5: Type = 85;
    pub const NUMPAD_6: Type = 86;
    pub const NUMPAD_7: Type = 87;
    pub const NUMPAD_8: Type = 88;
    pub const NUMPAD_9: Type = 89;
    pub const NUMPAD_ADD: Type = 90;
    pub const NUMPAD_BACKSPACE: Type = 91;
    pub const NUMPAD_CLEAR: Type = 92;
    pub const NUMPAD_CLEAR_ENTRY: Type = 93;
    pub const NUMPAD_COMMA: Type = 94;
    pub const NUMPAD_DECIMAL: Type = 95;
    pub const NUMPAD_DIVIDE: Type = 96;
    pub const NUMPAD_ENTER: Type = 97;
    pub const NUMPAD_EQUAL: Type = 98;
    pub const NUMPAD_MEMORY_ADD: Type = 99;
    pub const NUMPAD_MEMORY_CLEAR: Type = 100;
    pub const NUMPAD_MEMORY_RECALL: Type = 101;
    pub const NUMPAD_MEMORY_STORE: Type = 102;
    pub const NUMPAD_MEMORY_SUBTRACT: Type = 103;
    pub const NUMPAD_MULTIPLY: Type = 104;
    pub const NUMPAD_PAREN_LEFT: Type = 105;
    pub const NUMPAD_PAREN_RIGHT: Type = 106;
    pub const NUMPAD_SUBTRACT: Type = 107;
    pub const NUMPAD_SEPARATOR: Type = 108;
    pub const NUMPAD_UP: Type = 109;
    pub const NUMPAD_DOWN: Type = 110;
    pub const NUMPAD_RIGHT: Type = 111;
    pub const NUMPAD_LEFT: Type = 112;
    pub const NUMPAD_BEGIN: Type = 113;
    pub const NUMPAD_HOME: Type = 114;
    pub const NUMPAD_END: Type = 115;
    pub const NUMPAD_INSERT: Type = 116;
    pub const NUMPAD_DELETE: Type = 117;
    pub const NUMPAD_PAGE_UP: Type = 118;
    pub const NUMPAD_PAGE_DOWN: Type = 119;
    pub const ESCAPE: Type = 120;
    pub const F1: Type = 121;
    pub const F2: Type = 122;
    pub const F3: Type = 123;
    pub const F4: Type = 124;
    pub const F5: Type = 125;
    pub const F6: Type = 126;
    pub const F7: Type = 127;
    pub const F8: Type = 128;
    pub const F9: Type = 129;
    pub const F10: Type = 130;
    pub const F11: Type = 131;
    pub const F12: Type = 132;
    pub const F13: Type = 133;
    pub const F14: Type = 134;
    pub const F15: Type = 135;
    pub const F16: Type = 136;
    pub const F17: Type = 137;
    pub const F18: Type = 138;
    pub const F19: Type = 139;
    pub const F20: Type = 140;
    pub const F21: Type = 141;
    pub const F22: Type = 142;
    pub const F23: Type = 143;
    pub const F24: Type = 144;
    pub const F25: Type = 145;
    pub const FN: Type = 146;
    pub const FN_LOCK: Type = 147;
    pub const PRINT_SCREEN: Type = 148;
    pub const SCROLL_LOCK: Type = 149;
    pub const PAUSE: Type = 150;
    pub const BROWSER_BACK: Type = 151;
    pub const BROWSER_FAVORITES: Type = 152;
    pub const BROWSER_FORWARD: Type = 153;
    pub const BROWSER_HOME: Type = 154;
    pub const BROWSER_REFRESH: Type = 155;
    pub const BROWSER_SEARCH: Type = 156;
    pub const BROWSER_STOP: Type = 157;
    pub const EJECT: Type = 158;
    pub const LAUNCH_APP_1: Type = 159;
    pub const LAUNCH_APP_2: Type = 160;
    pub const LAUNCH_MAIL: Type = 161;
    pub const MEDIA_PLAY_PAUSE: Type = 162;
    pub const MEDIA_SELECT: Type = 163;
    pub const MEDIA_STOP: Type = 164;
    pub const MEDIA_TRACK_NEXT: Type = 165;
    pub const MEDIA_TRACK_PREVIOUS: Type = 166;
    pub const POWER: Type = 167;
    pub const SLEEP: Type = 168;
    pub const AUDIO_VOLUME_DOWN: Type = 169;
    pub const AUDIO_VOLUME_MUTE: Type = 170;
    pub const AUDIO_VOLUME_UP: Type = 171;
    pub const WAKE_UP: Type = 172;
    pub const COPY: Type = 173;
    pub const CUT: Type = 174;
    pub const PASTE: Type = 175;
    pub const MAX_VALUE: Type = 2147483647;
}
unsafe extern "C" {
    pub fn ghostty_key_event_new(allocator: *const Allocator, event: *mut KeyEvent)
        -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_key_event_free(event: KeyEvent);
}
unsafe extern "C" {
    pub fn ghostty_key_event_set_action(event: KeyEvent, action: KeyAction::Type);
}
unsafe extern "C" {
    pub fn ghostty_key_event_get_action(event: KeyEvent) -> KeyAction::Type;
}
unsafe extern "C" {
    pub fn ghostty_key_event_set_key(event: KeyEvent, key: Key::Type);
}
unsafe extern "C" {
    pub fn ghostty_key_event_get_key(event: KeyEvent) -> Key::Type;
}
unsafe extern "C" {
    pub fn ghostty_key_event_set_mods(event: KeyEvent, mods: Mods);
}
unsafe extern "C" {
    pub fn ghostty_key_event_get_mods(event: KeyEvent) -> Mods;
}
unsafe extern "C" {
    pub fn ghostty_key_event_set_consumed_mods(event: KeyEvent, consumed_mods: Mods);
}
unsafe extern "C" {
    pub fn ghostty_key_event_get_consumed_mods(event: KeyEvent) -> Mods;
}
unsafe extern "C" {
    pub fn ghostty_key_event_set_composing(event: KeyEvent, composing: bool);
}
unsafe extern "C" {
    pub fn ghostty_key_event_get_composing(event: KeyEvent) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_key_event_set_utf8(
        event: KeyEvent,
        utf8: *const ::std::os::raw::c_char,
        len: usize,
    );
}
unsafe extern "C" {
    pub fn ghostty_key_event_get_utf8(
        event: KeyEvent,
        len: *mut usize,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn ghostty_key_event_set_unshifted_codepoint(event: KeyEvent, codepoint: u32);
}
unsafe extern "C" {
    pub fn ghostty_key_event_get_unshifted_codepoint(event: KeyEvent) -> u32;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KeyEncoderImpl {
    _unused: [u8; 0],
}
pub type KeyEncoder = *mut KeyEncoderImpl;
pub type KittyKeyFlags = u8;
pub mod OptionAsAlt {
    pub type Type = ::std::os::raw::c_int;
    pub const FALSE: Type = 0;
    pub const TRUE: Type = 1;
    pub const LEFT: Type = 2;
    pub const RIGHT: Type = 3;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod KeyEncoderOption {
    pub type Type = ::std::os::raw::c_int;
    pub const CURSOR_KEY_APPLICATION: Type = 0;
    pub const KEYPAD_KEY_APPLICATION: Type = 1;
    pub const IGNORE_KEYPAD_WITH_NUMLOCK: Type = 2;
    pub const ALT_ESC_PREFIX: Type = 3;
    pub const MODIFY_OTHER_KEYS_STATE_2: Type = 4;
    pub const KITTY_FLAGS: Type = 5;
    pub const MACOS_OPTION_AS_ALT: Type = 6;
    pub const BACKARROW_KEY_MODE: Type = 7;
    pub const MAX_VALUE: Type = 2147483647;
}
unsafe extern "C" {
    pub fn ghostty_key_encoder_new(
        allocator: *const Allocator,
        encoder: *mut KeyEncoder,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_key_encoder_free(encoder: KeyEncoder);
}
unsafe extern "C" {
    pub fn ghostty_key_encoder_setopt(
        encoder: KeyEncoder,
        option: KeyEncoderOption::Type,
        value: *const ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn ghostty_key_encoder_setopt_from_terminal(encoder: KeyEncoder, terminal: Terminal);
}
unsafe extern "C" {
    pub fn ghostty_key_encoder_encode(
        encoder: KeyEncoder,
        event: KeyEvent,
        out_buf: *mut ::std::os::raw::c_char,
        out_buf_size: usize,
        out_len: *mut usize,
    ) -> Result::Type;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MouseEventImpl {
    _unused: [u8; 0],
}
pub type MouseEvent = *mut MouseEventImpl;
pub mod MouseAction {
    pub type Type = ::std::os::raw::c_int;
    pub const PRESS: Type = 0;
    pub const RELEASE: Type = 1;
    pub const MOTION: Type = 2;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod MouseButton {
    pub type Type = ::std::os::raw::c_int;
    pub const UNKNOWN: Type = 0;
    pub const LEFT: Type = 1;
    pub const RIGHT: Type = 2;
    pub const MIDDLE: Type = 3;
    pub const FOUR: Type = 4;
    pub const FIVE: Type = 5;
    pub const SIX: Type = 6;
    pub const SEVEN: Type = 7;
    pub const EIGHT: Type = 8;
    pub const NINE: Type = 9;
    pub const TEN: Type = 10;
    pub const ELEVEN: Type = 11;
    pub const MAX_VALUE: Type = 2147483647;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct MousePosition {
    pub x: f32,
    pub y: f32,
}
unsafe extern "C" {
    pub fn ghostty_mouse_event_new(
        allocator: *const Allocator,
        event: *mut MouseEvent,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_mouse_event_free(event: MouseEvent);
}
unsafe extern "C" {
    pub fn ghostty_mouse_event_set_action(event: MouseEvent, action: MouseAction::Type);
}
unsafe extern "C" {
    pub fn ghostty_mouse_event_get_action(event: MouseEvent) -> MouseAction::Type;
}
unsafe extern "C" {
    pub fn ghostty_mouse_event_set_button(event: MouseEvent, button: MouseButton::Type);
}
unsafe extern "C" {
    pub fn ghostty_mouse_event_clear_button(event: MouseEvent);
}
unsafe extern "C" {
    pub fn ghostty_mouse_event_get_button(
        event: MouseEvent,
        out_button: *mut MouseButton::Type,
    ) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_mouse_event_set_mods(event: MouseEvent, mods: Mods);
}
unsafe extern "C" {
    pub fn ghostty_mouse_event_get_mods(event: MouseEvent) -> Mods;
}
unsafe extern "C" {
    pub fn ghostty_mouse_event_set_position(event: MouseEvent, position: MousePosition);
}
unsafe extern "C" {
    pub fn ghostty_mouse_event_get_position(event: MouseEvent) -> MousePosition;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MouseEncoderImpl {
    _unused: [u8; 0],
}
pub type MouseEncoder = *mut MouseEncoderImpl;
pub mod MouseTrackingMode {
    pub type Type = ::std::os::raw::c_int;
    pub const NONE: Type = 0;
    pub const X10: Type = 1;
    pub const NORMAL: Type = 2;
    pub const BUTTON: Type = 3;
    pub const ANY: Type = 4;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod MouseFormat {
    pub type Type = ::std::os::raw::c_int;
    pub const X10: Type = 0;
    pub const UTF8: Type = 1;
    pub const SGR: Type = 2;
    pub const URXVT: Type = 3;
    pub const SGR_PIXELS: Type = 4;
    pub const MAX_VALUE: Type = 2147483647;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct MouseEncoderSize {
    pub size: usize,
    pub screen_width: u32,
    pub screen_height: u32,
    pub cell_width: u32,
    pub cell_height: u32,
    pub padding_top: u32,
    pub padding_bottom: u32,
    pub padding_right: u32,
    pub padding_left: u32,
}
pub mod MouseEncoderOption {
    pub type Type = ::std::os::raw::c_int;
    pub const EVENT: Type = 0;
    pub const FORMAT: Type = 1;
    pub const SIZE: Type = 2;
    pub const ANY_BUTTON_PRESSED: Type = 3;
    pub const TRACK_LAST_CELL: Type = 4;
    pub const MAX_VALUE: Type = 2147483647;
}
unsafe extern "C" {
    pub fn ghostty_mouse_encoder_new(
        allocator: *const Allocator,
        encoder: *mut MouseEncoder,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_mouse_encoder_free(encoder: MouseEncoder);
}
unsafe extern "C" {
    pub fn ghostty_mouse_encoder_setopt(
        encoder: MouseEncoder,
        option: MouseEncoderOption::Type,
        value: *const ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn ghostty_mouse_encoder_setopt_from_terminal(encoder: MouseEncoder, terminal: Terminal);
}
unsafe extern "C" {
    pub fn ghostty_mouse_encoder_reset(encoder: MouseEncoder);
}
unsafe extern "C" {
    pub fn ghostty_mouse_encoder_encode(
        encoder: MouseEncoder,
        event: MouseEvent,
        out_buf: *mut ::std::os::raw::c_char,
        out_buf_size: usize,
        out_len: *mut usize,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_paste_is_safe(data: *const ::std::os::raw::c_char, len: usize) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_paste_encode(
        data: *mut ::std::os::raw::c_char,
        data_len: usize,
        bracketed: bool,
        buf: *mut ::std::os::raw::c_char,
        buf_len: usize,
        out_written: *mut usize,
    ) -> Result::Type;
}
pub mod SnapshotDecoderOption {
    pub type Type = ::std::os::raw::c_int;
    pub const GHOSTTY_SNAPSHOT_DECODER_OPT_MAX_CONTINUATION_BYTES: Type = 0;
    pub const GHOSTTY_SNAPSHOT_DECODER_OPT_RETAIN_CONTINUATION: Type = 1;
    pub const GHOSTTY_SNAPSHOT_DECODER_OPT_MAX_VALUE: Type = 2147483647;
}
pub mod SnapshotDecoderData {
    pub type Type = ::std::os::raw::c_int;
    pub const INVALID: Type = 0;
    pub const MAX_CONTINUATION_BYTES: Type = 1;
    pub const SOURCE_OFFSET: Type = 2;
    pub const HISTORY_ROWS_PRIMARY: Type = 3;
    pub const HISTORY_ROWS_ALTERNATE: Type = 4;
    pub const PROGRESS_SCREEN: Type = 5;
    pub const PROGRESS_ROWS: Type = 6;
    pub const PROGRESS_REMAINING: Type = 7;
    pub const RETAIN_CONTINUATION: Type = 8;
    pub const MAX_VALUE: Type = 2147483647;
}
unsafe extern "C" {
    pub fn ghostty_snapshot_encode(terminal: Terminal, writer: Writer) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_snapshot_encode_buf(
        terminal: Terminal,
        buf: *mut u8,
        buf_len: usize,
        out_written: *mut usize,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_snapshot_encode_alloc(
        terminal: Terminal,
        allocator: *const Allocator,
        out_ptr: *mut *mut u8,
        out_len: *mut usize,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_snapshot_decoder_new(
        allocator: *const Allocator,
        decoder: *mut SnapshotDecoder,
        reader: Reader,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_snapshot_decoder_new_buf(
        allocator: *const Allocator,
        decoder: *mut SnapshotDecoder,
        ptr: *const u8,
        len: usize,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_snapshot_decoder_free(decoder: SnapshotDecoder);
}
unsafe extern "C" {
    pub fn ghostty_snapshot_decoder_set(
        decoder: SnapshotDecoder,
        option: SnapshotDecoderOption::Type,
        value: *const ::std::os::raw::c_void,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_snapshot_decoder_ready(
        decoder: SnapshotDecoder,
        terminal: *mut Terminal,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_snapshot_decoder_next(decoder: SnapshotDecoder) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_snapshot_decoder_decode(
        decoder: SnapshotDecoder,
        terminal: *mut Terminal,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_snapshot_decoder_get(
        decoder: SnapshotDecoder,
        data: SnapshotDecoderData::Type,
        out: *mut ::std::os::raw::c_void,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_snapshot_decoder_get_multi(
        decoder: SnapshotDecoder,
        count: usize,
        keys: *const SnapshotDecoderData::Type,
        values: *mut *mut ::std::os::raw::c_void,
        out_written: *mut usize,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn ghostty_unicode_codepoint_width(cp: u32) -> u8;
}
unsafe extern "C" {
    pub fn ghostty_unicode_grapheme_width(cps: *const u32, len: usize, width: *mut u8) -> usize;
}
unsafe extern "C" {
    pub fn mightty_ghostty_render_observe(state: RenderState, terminal: Terminal) -> Result::Type;
}
unsafe extern "C" {
    pub fn mightty_ghostty_vt_write(terminal: Terminal, data: *const u8, len: usize) -> u64;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MighttyGhosttySearchImpl {
    _unused: [u8; 0],
}
pub type MighttyGhosttySearch = *mut MighttyGhosttySearchImpl;
pub mod MighttyGhosttySearchStep {
    pub type Type = ::std::os::raw::c_int;
    pub const PENDING: Type = 0;
    pub const COMPLETE: Type = 1;
    pub const MAX_VALUE: Type = 2147483647;
}
pub mod MighttyGhosttySearchDirection {
    pub type Type = ::std::os::raw::c_int;
    pub const NEXT: Type = 0;
    pub const PREVIOUS: Type = 1;
    pub const MAX_VALUE: Type = 2147483647;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct MighttyGhosttySearchRange {
    pub start_x: u16,
    pub start_y: u32,
    pub end_x: u16,
    pub end_y: u32,
}
unsafe extern "C" {
    pub fn mightty_ghostty_search_new(
        terminal: Terminal,
        query: *const u8,
        query_len: usize,
        out_search: *mut MighttyGhosttySearch,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn mightty_ghostty_search_free(search: MighttyGhosttySearch);
}
unsafe extern "C" {
    pub fn mightty_ghostty_search_probe(
        search: MighttyGhosttySearch,
        out_match: *mut bool,
        out_buffer_changed: *mut bool,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn mightty_ghostty_search_step(
        search: MighttyGhosttySearch,
        out_step: *mut MighttyGhosttySearchStep::Type,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn mightty_ghostty_search_ranges(
        search: MighttyGhosttySearch,
        ranges: *mut MighttyGhosttySearchRange,
        capacity: usize,
        out_len: *mut usize,
    ) -> Result::Type;
}
unsafe extern "C" {
    pub fn mightty_ghostty_search_select(
        search: MighttyGhosttySearch,
        direction: MighttyGhosttySearchDirection::Type,
        out_range: *mut MighttyGhosttySearchRange,
    ) -> Result::Type;
}
